### ISSUE TITLE
ng add ng-alain <project name> Error

### ISSUE THREAD

**Issue by Anberm** [cipchk/delon#100]
- ng-alain version: 1.0.8
- Angular CLI: 6.0.8
- Node: 9.5.0
- OS: win32 x64
- Angular: 6.0.4

![tim 20180613161519](https://user-images.githubusercontent.com/34148806/41338601-3e8f1f80-6f25-11e8-91ec-b7956bd893a0.png)

## 重现步骤，Steps to reproduce
1. ng new alainEg
2. cd alainEg
3. ng add ng-alain alainEg
4. npm ERR! Unexpected end of JSON input while parsing near '...p":false,"publish_tim'

**Comment by cipchk** [comment]
I think the reason for `npm i`, that auto call `npm i ` in last step of the `ng add ng-alain` command.

**Comment by Anberm** [comment]
yes,but this caused me to use the command npm install in the future is wrong.If I don't use the ALAIN command,and I just copy the directory, which is fine, so I think it has to do with the ALAIN command

**Comment by cipchk** [comment]
you can following steps:

- `ng g ng-alain:plugin yarn`
- removed `node_modules` `package-lock.json`
- `yarn`

or 

- removed `node_modules` `package-lock.json`
- `npm i`

**Comment by Anberm** [comment]
Wrong in .npmrc [packages\schematics\plugin\plugin.npm.ts],There are problems in the source registry=https://registry.npm.taobao.org，Just get rid of this source.
This is true:
sass_binary_site=https://npm.taobao.org/mirrors/node-sass/
phantomjs_cdnurl=https://npm.taobao.org/mirrors/phantomjs/
electron_mirror=https://npm.taobao.org/mirrors/electron/
