### ISSUE TITLE
simple-table 能否支持0基索引

### ISSUE THREAD

**Issue by pholance** [cipchk/delon#108]
当data绑定到url时，能否指定pi请求参数值为“当前页码-1”。毕竟某些服务器采取了0基索引。

**Comment by cipchk** [comment]
不支持。

**Comment by uded** [comment]
Actually, I would second that request. It would make sense to introduce a single param to count pages from either 0 or 1. A lot of backend frameworks will assume that no param or 0 is the starting page and it should be fairly simple to make this dependant on config on the frontend framework side as this `1` as a starting page is actually unusual one...

**Comment by cipchk** [comment]
@uded  @pholance  
https://ng-alain.com/components/simple-table#simple-table  pls refer to `[zeroIndexedOnPage]` argument.
