### ISSUE TITLE
simple-table使用any[]作为data，手工httpClient异步读取数据时，pagination页码错误

### ISSUE THREAD

**Issue by pholance** [cipchk/delon#109]
- ng-alain version: 1.1.1
- Angular version: 6.0.5

## 重现步骤：
使用simple-table
绑定[data]为某个any[]类型
绑定(change)，翻页时采用httpClient请求新数据，并重新赋值给[data]
页面中翻页时，页码会自动跳转到1

## 其它说明：
此现象仅在使用`HttpClient`或`_HttpClient`时出现，如参考官方示例使用`of`制作的异步数据时，页码是正常的。
页码虽然会自动跳转，但不会发起`change`事件。

**Comment by cipchk** [comment]
duplcated of https://github.com/cipchk/ng-alain/issues/524
