### ISSUE TITLE
完全自定义小部件中按钮会导致表单提交

### ISSUE THREAD

**Issue by limingyao-xx** [cipchk/delon#115]
完全自定义小部件中如下：
`  <sf-item-wrap [id]="id" [schema]="schema" [ui]="ui" [showError]="showError" [error]="error"
                  [showTitle]="schema.title">
      <button nz-button nzType="primary">标注</button>
</sf-item-wrap>
`
当点击按钮时会导致表单提交

**Comment by cipchk** [comment]
指定 `button` 的 `type="button"` 值。
