### ISSUE TITLE
点击notice某一行数据，关闭notice,把nzVisible改成双向数据绑定能解决，但会有报错

### ISSUE THREAD

**Issue by smile2014** [cipchk/delon#116]
selector: 'notice-icon',
  template: `
    <nz-badge *ngIf="data?.length === 0" [nzCount]="count">
      <i class="anticon anticon-bell"></i>
    </nz-badge>
    <apes-popover *ngIf="data?.length > 0"
      [(nzVisible)]="popoverVisible" 

Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'loading: false'. Current value: 'loading: true'.

**Comment by screamsyk** [comment]
怎么解决的呢？
