### ISSUE TITLE
reuse-tab 能否增加图标

### ISSUE THREAD

**Issue by tucke** [cipchk/delon#119]
reuse-tab 个人还是挺喜欢的，但是发现，tab 打开过多之后，便很难快速区分！如果每个 tab 在 title 的左边能自定义一个小图标，可能会更好一点！: )

**Comment by cipchk** [comment]
你可以继承 https://github.com/cipchk/delon/blob/master/packages/abc/reuse-tab/reuse-tab.component.ts   重写HTML模板。
