### ISSUE TITLE
【动态表单】提供一个可选配置，让字段为空时，不传递给后端

### ISSUE THREAD

**Issue by Null-Ouwenjie** [cipchk/delon#124]
【功能建议】
使用动态表单 sf 时，假如有一个 id 输入框，提供根据 id 查询记录的功能。
用户在输入 id 进行查询后，又删掉了输入框的内容，再次查询。
此时发起的 http 里，会将 id : '' 带上，这不是查询所期待的。

因为，后端的 API 对查询参数可能会有要求，非空，长度限制等，这时候传 id:'' 是直接报错了。
同样，如果不是 id ，而是 email ，那就更明显了，传了 email : ''，给后端，后端是不通过这种参数的。

由于不同后端有不一样的参数策略，所以，我期望这是一个【可选项】，为空的参数就不传。

**Comment by cipchk** [comment]
可以自行写一个封闭方法，在提交数据前进行剔除。

**Comment by Null-Ouwenjie** [comment]
了解了，是我之前对使用方法理解不够。
