### ISSUE TITLE
@delon/form   上传组件当网络发生错误时会在控制台出现错误，不知道是不是bug

### ISSUE THREAD

**Issue by super-organism** [cipchk/delon#125]
源代码
@Component({
  selector: 'app-upload-simple',
  template: `<sf [schema]="schema" (formSubmit)="submit($event)"></sf>`,
})
export class EmanageEventUploadComponent {
  schema: SFSchema = {
    properties: {
      drag: {
        type: 'string',
        title: 'Drag',
        ui: {
          widget: 'upload',
          action: '/upload',
          resReName: 'resource_id',
          type: 'drag',
        },
      },
    },
  };
  constructor(public msg: NzMessageService) {}
  submit(value: any) {
    this.msg.success(JSON.stringify(value));
  }
}

错误提示
core.js:1633 ERROR TypeError: Cannot set property 'error' of undefined
    at Object.NzUploadComponent.onError (antd.js:34173)
    at Object.onError (antd.js:33844)
    at SafeSubscriber._error (antd.js:33895)

**Comment by super-organism** [comment]
今天重试发现如果使用angular cli 创建的应用是没有问题的 
但是如果使用 ng-alain创建的应用就会出现以上问题
具体测试代码我已经放在https://github.com/super-organism/test.git
在访问http://127.0.0.1:4200/#/aaa/aaa上传文件时就回出现以上问题
刚接触前端技术，在线实例尚不会搭建，望见谅

**Comment by cipchk** [comment]
the stackblitz templat url:

https://stackblitz.com/edit/ng-alain-setup
or 
https://stackblitz.com/edit/ng-alain

**Comment by super-organism** [comment]
在你这两个实例上跑是没问题的，但是我使用ng add ng-alain 创建的应用是有问题的 
我的步骤：
ng new demo --style less  
cd demo
ng add ng-alain 
ng g ng-alain:module trade
ng g ng-alain:view view -m=trade 
在view compent中调用上传组件就会报错 ，全部使用的默认数据，希望你本地跑一下

**Comment by super-organism** [comment]
https://stackblitz.com/edit/ng-alain   在线实例  
点击编辑，弹出modal后，点击关闭按钮 就会出现错误提示
推测是 sf组件问题

**Comment by cipchk** [comment]
我不没有看到什么错误？能否描述你问题的重现具体步骤。

**Comment by super-organism** [comment]
在新窗口内 测试 会触发
![image](https://user-images.githubusercontent.com/29723072/43116037-6acceafe-8f38-11e8-83e5-c87bb38b8480.png)
打开再关闭modal 就出错  （难道是我的浏览器？？？）
![image](https://user-images.githubusercontent.com/29723072/43116049-8407374a-8f38-11e8-8dec-7232d257ffd2.png)
