### ISSUE TITLE
ACLGuard with redirect to Login Page if token is missing

### ISSUE THREAD

**Issue by uded** [cipchk/delon#127]
In my use case, I have a scenario of going from one static page (landing page) to any of the active, business logic pages. There is no request made hence DefaultIntercept will not work here. I would like to `ACLGuard` to actually check if there is a token or any other form of confirmation that the user was authenticated and not just redirect to 403 - which is my current observed scenario. Especially since I am using an auth service, yet I couldn't find any connection between those two. 

Please, do correct me if I missed something obvious, but from what I can see in the code ACL is completely independent from Auth...

**Comment by cipchk** [comment]
I think Authorization and Access Control List is two things.

i will add ACLGuard in next version.

**Comment by uded** [comment]
Generally, but only generally, I do agree with you. But in practice - at least in my last 20 years of experience - those two things are rather closely coupled and while you might require authentication without authorization, in most cases (like 99% of them) you will authenticate to authorize.

I would expect that delon/auth would make it possible to inject authentication context into delon/acl in a form of checking if the user is authenticated in the first place, possibly propagating roles or other forms of authorization tokens with login, etc. This is how 90% of authorization and authentication frameworks work.
