### ISSUE TITLE
reusetab中tab自己消失的问题

### ISSUE THREAD

**Issue by wanghaolu** [cipchk/delon#13]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

reusetab中新增的tab后在点击倒数第二个时最后一个就会自己消失

![2018-01-10_16-11-51](https://user-images.githubusercontent.com/9586655/34764323-1458bc3c-f629-11e7-9351-cd00c77359f8.gif)

顺便问一下，我通过参数化路由配置的   detail/:id
在大于1个detail路由被打开的情况下reuse.service保存的detail/xxxx状态并不是每个都独立的，而是在切换的时候被当前激活的路由所覆盖了。
如果采用 https://angular.io/tutorial/toh-pt5#extract-the-id-route-parameter 中的那种方法来获取路由参数就会导致只保留了最后激活的detail的数据，之前的数据就会丢失。这个是angular路由本身的问题导致的还是reusetab的问题？
## Environment

<pre><code>
Angular version: X.Y.Z

delon version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by wanghaolu** [comment]
第二个问题好像叙述的有些麻烦
就是在同一个路由不同参数的情况好像不会激活ReuseTabStrategy中的retrieve方法，导致状态不能复用

**Comment by wanghaolu** [comment]
好像是reuse.service中的shouldReuseRoute导致的

```javascript
   /**
     * 决定是否应该进行复用路由处理
     */
    shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
        return future.routeConfig === curr.routeConfig;
    }
```
同一个路由参数不同但routeConfig是一致的，这样就导致不能正确判断是否获取缓存数据

**Comment by cipchk** [comment]
1、这一问题我没办法处理，原因是每个人的使用情况不同，会关闭的可能是当前路由没有被 复用到。
2、路由以URL为准，参数有分路由参数还是 QueryString，这个要依情况而定。

**Comment by wanghaolu** [comment]
我看了下代码，这两个问题好像具有关联性

reuse-tab.service.ts
```javascript
    /**
     * 决定是否应该进行复用路由处理
     */
    shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
        return future.routeConfig === curr.routeConfig;
    }
```
在相同路由但路由参数不同的情况下这个地方判断前后路由是否相同时始终为true，导致路由状态没有复用。而状态保存时在路由离开时发生，导致离开的路由状态没有保存就进入到下一个路由地址。
不知道猜测是否正确

**Comment by cipchk** [comment]
的确有这种可能，我需要进一步核实

**Comment by cipchk** [comment]
`reuse-tab` 组件，在 `0.6.0` 新增了一个 `debug` 属性，我建议你能否开启它，然后看能否了解更多细节。

**Comment by wanghaolu** [comment]
![2018-01-15_12-55-37](https://user-images.githubusercontent.com/9586655/34927833-1b627bde-f9f4-11e7-804f-0623a5079c53.png)

**Comment by cipchk** [comment]
#sotre 表示存储，我好像没有看到第二次的详情页在回到上一详情页时触发存储的动作；还是说log有遗漏。

**Comment by wanghaolu** [comment]
在打开第二个详情页面的时候没有进行状态恢复，应该是在判断URL的时候以为是同一个地址就没有执行。

就像我之前说同一个路由配置不同路由参数情况下routeConfig是一致的，导致在判断的时候以为是相同的页面，就没有执行状态重用的相关操作

**Comment by cipchk** [comment]
能否利用 https://stackblitz.com/edit/ng-alain-setup 重现一下你的情况？

**Comment by wanghaolu** [comment]
这是我在shouldReuseRoute里加了debug方法后的截图
![2018-01-15_12-55-37](https://user-images.githubusercontent.com/9586655/34928212-0217dfb8-f9f7-11e7-9862-371cac184c51.png)

**Comment by cipchk** [comment]
shouldReuseRoute 不是判断的标准，我本地无法重现你说的这种情况，若你愿意麻烦你在 stackblitz 重现你的情况。

**Comment by wanghaolu** [comment]
我之前就在stackblitz里面实现过，但一直报错，我只有在本地建个项目发给你

**Comment by cipchk** [comment]
不会的，若涉及到菜单，可以在 AppModule 中模拟并调用 `add` 即可。

**Comment by wanghaolu** [comment]
@cipchk 
https://stackblitz.com/edit/ng-alain-setup-qusdbh

**Comment by smile2014** [comment]
这个问题大家怎么解决的阿
