### ISSUE TITLE
主题系统文档说明与实际代码不符合

### ISSUE THREAD

**Issue by neo-miteno** [cipchk/delon#130]
官网中的关于主题系统的文档：https://ng-alain.com/theme/getting-started， 第一句话是：**@delon/theme 是 ng-alain 架手脚唯一必须引入的模块。** 。 这个与实际代码不符合，实际代码中delon/packages/theme/services/menu/menu.service.ts 却用了ACL的模块。 请考虑解决这个问题，要么修改文档，要么修改代码，不然给初学者容易造成困恼。

**Comment by cipchk** [comment]
ACL 模块是一种可选的依赖，但你不需要 ACL 时（但 `@delon/acl` 类库依赖需要安装）是不会被打包进任何相关 ACL 的代码。

**Comment by neo-miteno** [comment]
嗯，我是不需要ACL， 但theme模块的menu.service.ts需要啊。 这意味着我导入theme模块的同时，也必须导入ACL。

**Comment by cipchk** [comment]
若不需要 ACL，但依然需要安装 `@delon/acl` 类库。

> 可以参阅 angular.io 了解关于模块相关章节。
