### ISSUE TITLE
simple-table 的固定列的 left 计算有误

### ISSUE THREAD

**Issue by shuizhongxiong** [cipchk/delon#132]
- ng-alain version: 1.2.0
- Angular version: 6.1.0

## simple-table 左侧固定列超过两个时，往右移动会遮盖之前的列

移动前：
![wx20180803-175328](https://user-images.githubusercontent.com/13978010/43636981-2f140f9a-9746-11e8-9a1a-6a8dccfcf79e.png)

移动后：
![wx20180803-175429](https://user-images.githubusercontent.com/13978010/43637033-4dcc72f6-9746-11e8-89f5-319beec71eb8.png)

**Comment by cipchk** [comment]
我看[固定列](https://ng-alain.com/components/simple-table#components-simple-table-fixed) 并没有这种情况，麻烦提供一个重现示例。

**Comment by shuizhongxiong** [comment]
在 StackBlitz 中打开

**Comment by shuizhongxiong** [comment]
请问 npm 包的代码有更新么，我本地更新到 1.3.0 后还是有这个问题，然后看了一下 node_module 里面的代码还是旧的。

**Comment by cipchk** [comment]
等待下一版本

**Comment by shuizhongxiong** [comment]
哦哦，好的，谢谢哈🌺
