### ISSUE TITLE
simple-table 点击排序后只 emit 数据

### ISSUE THREAD

**Issue by shuizhongxiong** [cipchk/delon#133]
#### 现状
使用 simple-table 的排序功能，点击排序按钮后自动 sort

#### 代码

```js
startColumns: SimpleTableColumn[] = [
   { title: '覆盖渗透率(%)', index: 'percentage' },
    { title: '覆盖月增长率(%)', index: 'percentage_mom' },
    { title: '覆盖季增长率(%)', index: 'percentage_sos' },
    { title: '覆盖季增长率(%)', index: 'percentage_yoy' }
  ].map((item: any) => {
    item.sorter = () => true;
    return item;
  });
```

#### 希望
希望只 emit 相关数据，不进行 sort 操作。因为我只需要 sort 按钮的相关信息，然后传给后端，不用前端排序。

[这块](https://github.com/cipchk/delon/blob/1a93cdb2433a0e1f300fac6107f6ecbf78318138/packages/abc/simple-table/simple-table.component.ts#L641) 加个什么参数判断啥的。

**Comment by cipchk** [comment]
Will not support
