### ISSUE TITLE
建议simple-tabl 在自动去除 extraParams 的 null 值

### ISSUE THREAD

**Issue by renfan** [cipchk/delon#136]
- ng-alain version:1.3.1
- Angular version: 6.1.0

<img width="980" alt="qq20180816-082918 2x" src="https://user-images.githubusercontent.com/3666795/44180357-819e4180-a12e-11e8-9cbe-4308c6bad6b2.png">
这里我用的是nz-form如果重置后传参会包含null

```
list?pi=1&ps=10&name=null&display_name=null
```

之前用的simple-form

```
 <sf mode="search" [schema]="searchSchema" [formData]="params" (formSubmit)="st.reset($event)"
      (formReset)="st.reset(params)"></sf>
```
不会有这个问题。
]
目前我是这样处理的
```
//html的simple-table中把params改成getParams()
[extraParams]="getParams()"

//这是getParams()函数
getParams() {
    return pickBy(this.params, (v => !isNull(v)));
  }
```
不知道能不能做个自动去除，或者已经有其他办法。

**Comment by cipchk** [comment]
其实 `_HttpClient` 支持对空值过滤的功能，但是 `simple-table` 并不会包含这种支持，建议从 HTTP 拦截器入手。
