### ISSUE TITLE
sidebar-nav 分组问题

### ISSUE THREAD

**Issue by jackzhum** [cipchk/delon#140]
sidebar-nav 的菜单数据必须是
`
{
       "text": "主导航",
      "i18n": "main_navigation",
      "group": true,
      "hideInBreadcrumb": true,
      "children": [
              {
                    "text": "仪表盘V1",
                    "link": "/dashboard/v1",
                    "i18n": "dashboard_v1"
              }
       ]
}
`
上面这种格式，也就是需要菜单连接外面包一层group，如果我不需要分组，直接在菜单上显示链接：
`
  {
                    "text": "仪表盘V1",
                    "link": "/dashboard/v1",
                    "i18n": "dashboard_v1"
          }
`
这样的话，菜单只显示名称，没有图标，没有链接，不能点击。

**Comment by cipchk** [comment]
至少需要一层分组

> feat: 增加 `hideGroup` 属性用于表示不显示组名。
