### ISSUE TITLE
FormProperty中调用SchemaValidatorFactory.createValidatorFn类型检查错误

### ISSUE THREAD

**Issue by Kiuyam** [cipchk/delon#143]
- ng-alain version: 1.3.2
- Angular version: 6.1.0

## 【必填项】重现链接，Reproduction link
![image](https://user-images.githubusercontent.com/25220646/44505845-1cba8c80-a6d6-11e8-813b-3e47b09905d1.png)
![image](https://user-images.githubusercontent.com/25220646/44505872-42e02c80-a6d6-11e8-86e7-fcfcce58f5fa.png)

## 重现步骤，Steps to reproduce

##这样可以避免  不确定是否会有其他影响。还有一些方法也会出现这个问题。
![image](https://user-images.githubusercontent.com/25220646/44505912-7f138d00-a6d6-11e8-8bbc-dd2aee4fd881.png)

**Comment by cipchk** [comment]
这对使用上有什么影响吗？

**Comment by Kiuyam** [comment]
没有，只是down下来报错有点难受而已。。。。
