### ISSUE TITLE
sf 组件 在mode 为 search时  submit 按钮国际化显示不正确

### ISSUE THREAD

**Issue by lumeng689** [cipchk/delon#146]
- ng-alain version: 1.3.3
- Angular version: 6.2.2

## 【必填项】重现链接，Reproduction link
![image](https://user-images.githubusercontent.com/1297158/44974830-638c6a00-af93-11e8-8da1-5609aef51609.png)

## 重现步骤，Steps to reproduce

<sf mode="search" [schema]="searchSchema"
        [button]="button"
        (formSubmit)="onQuery($event)"
        (formReset)="onReset($event)"></sf>

切换英文时 submit  按钮文字不按照设定，而是默认显示 [搜索]

**Comment by cipchk** [comment]
自行维护 `button.submit` 和 `button.reset` 值，`sf` 并没有对国际化做任何处理。

**Comment by lumeng689** [comment]
@cipchk   非常感谢您的回复， 国际化是通过定制button来维护的， 只是 当sf控件的 mode="search"的时候， button.submit 好像被覆盖掉了。button.reset是起作用的。看源码，这块是不是不要覆盖呢？

<pre>
<code>
 @Input()
  set mode(value: 'default' | 'search' | 'edit') {
    switch (value) {
      case 'search':
        this.layout = 'inline';
        this.firstVisual = false;
        this.liveValidate = false;
        if (this._btn) this._btn.submit = '搜索';  // 这个地方的值 要不要不设置呢？
        break;
      case 'edit':
        this.layout = 'horizontal';
        this.firstVisual = false;
        this.liveValidate = true;
        if (this._btn) this._btn.submit = '保存';
        break;
    }
    this._mode = value;
  }
</code>
</pre>
