### ISSUE TITLE
升级到0.6.1后所有路由都会导致页面刷新

### ISSUE THREAD

**Issue by wanghaolu** [cipchk/delon#20]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

只进行了升级，其他代码没动过，所有路由都会导致页面整体刷新
![tim 20180117103711](https://user-images.githubusercontent.com/9586655/35022696-3d0a7320-fb72-11e7-8b6e-46225a09dcfc.png)

**Comment by cipchk** [comment]
[demo](https://cipchk.github.io/ng-alain) 不存在这一问题，你看是否匹配模式上有问题。

**Comment by wanghaolu** [comment]
如果我没看错demo页也是出现了全局刷新的问题
点reusetab上的链接的时候左侧菜单栏和顶部菜单栏都出现了闪动

**Comment by cipchk** [comment]
的确如此，`0.6.1` 改变的路由复用，倒置了从根组件再子组件都复用了，这的确是一个问题。
