### ISSUE TITLE
关于@delon/abc独立使用的问题

### ISSUE THREAD

**Issue by 81519434** [cipchk/delon#22]
我们现在的项目不是基于ng-alain手脚架的，但是我们急切的需要使用其中的reuse-tab组件。
于是我们 
cnpm install @delon/abc 0.6.2。
cnpm install @delon/theme 0.6.2。
cnpm install @delon/acl 0.6.2。

![image](https://user-images.githubusercontent.com/9690089/35132246-31b425ae-fd05-11e7-9090-91247474cbc0.png)

一旦引入了这个Module，就会报错

![image](https://user-images.githubusercontent.com/9690089/35132263-4a62770e-fd05-11e7-8e71-acab35e6d16e.png)

那么到底@delon/abc支持在ng-alain手脚架之外的项目中使用吗？

**Comment by cipchk** [comment]
保持相关依赖的安装，但是不必担心会增加包体大小，因为 `reuse-tab` 组件是一个清洁的。

我会增强依赖的配置。

**Comment by 81519434** [comment]
好的，谢谢你。

**Comment by 81519434** [comment]
我单独使用reuse-tab的时候
在app.module.ts里面声明了AdReuseTabModule
我们也模仿你构造了一个简单的StartupService，然后调用了load方法，往MenuService填充数据，但是报错。
![image](https://user-images.githubusercontent.com/9690089/35203808-058d853a-ff65-11e7-8052-a5218a2b3096.png)
我这里该怎么整合呢？

**Comment by cipchk** [comment]
抱歉，我不是很清楚的结构状态，但是出错很明显就是未注册服务 `MenuService`

**Comment by 81519434** [comment]
对的，我没有发现你在手脚架上有在privide上声明这个MenuService。所以我不知道该在哪里进行provide声明。app.module.ts吗？

**Comment by cipchk** [comment]
对 `reuse-tab` 而言 `MenuService` 是可选的，注不注入都不影响使用，请核实你的 @delon/abc 版本。

**Comment by 81519434** [comment]
如果要初始化菜单数据，不是一定要调用MenuService 的add方法把json穿进去初始化吗？
![image](https://user-images.githubusercontent.com/9690089/35204230-b79dab72-ff67-11e7-842c-fd69626d36e8.png)

**Comment by cipchk** [comment]
`MenuService` 是 @delon/theme  的一部分，非 ng-alain 脚手架没有必要导入它。

**Comment by 81519434** [comment]
路由是这样配置的

![image](https://user-images.githubusercontent.com/9690089/35208615-42594660-ff84-11e7-8008-276d5c671052.png)
![image](https://user-images.githubusercontent.com/9690089/35208632-508188ce-ff84-11e7-9ac2-02800df9f216.png)
这个是子路由，所以path为空

![image](https://user-images.githubusercontent.com/9690089/35208641-57288b32-ff84-11e7-90d2-20da64ee8589.png)
这个是父路由。


切换 路由时报错
![image](https://user-images.githubusercontent.com/9690089/35208593-2ce04720-ff84-11e7-97a3-091c2deed399.png)
![image](https://user-images.githubusercontent.com/9690089/35208605-3719626c-ff84-11e7-9e49-7d76d68e537c.png)


版本是 "@delon/abc": "^0.6.2"

**Comment by 81519434** [comment]
是我少配置了什么东西吗

**Comment by cipchk** [comment]
duplcated of [#244](https://github.com/cipchk/ng-alain/issues/244), i will fixed this at night.

**Comment by 81519434** [comment]
谢谢

**Comment by 81519434** [comment]
![image](https://user-images.githubusercontent.com/9690089/35262930-acadbef6-0051-11e8-82d7-122413dd9813.png)
![image](https://user-images.githubusercontent.com/9690089/35262938-b57dcdd2-0051-11e8-9a98-6ec640fe1228.png)

 在 我切换路由之后，tab只是内容和标题变了，并没有新增tab，这个地方是要多余什么配置吗？

**Comment by cipchk** [comment]
应该是匹配模式，可以设定为 `<reuse-tab [mode]="2"></reuse-tab>` 以URL模式运行。

**Comment by 81519434** [comment]
这样设置了也一样没有用，也没有报错。

**Comment by cipchk** [comment]
除此之外我想不到有别的因素，或许你可以打开 `debug` 模式，了解一些细节。
