### ISSUE TITLE
feature:reusetab增加能控制tab是否允许关闭的功能

### ISSUE THREAD

**Issue by wanghaolu** [cipchk/delon#23]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

有时候我们希望某个tab常驻reusetab中，不能被关闭。
可以通过reusetabservice来设置当前tab是否可以关闭，向设置title差不多的方式

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
正在考虑增加 `closeable` 选项，请持续关注。

**Comment by Y2zz** [comment]
或者关闭 tab 功能？
