### ISSUE TITLE
某些情况下reusetab标题混乱

### ISSUE THREAD

**Issue by wanghaolu** [cipchk/delon#25]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link

复现代码
[delontest.zip](https://github.com/cipchk/delon/files/1648473/delontest.zip)

## Steps to reproduce

![2018-01-20_11-04-56](https://user-images.githubusercontent.com/9586655/35179265-cfa84372-fdd1-11e7-9d0c-0a8e2330a9c9.gif)

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
请提供一下https://stackblitz.com/edit/ng-alain-setup可重现的示例。

**Comment by wanghaolu** [comment]
能将就用一下我上传的那个代码么，我在stackblitz里面同样的代码要报错，还在研究是什么情况。
我上传的那个代码直接npm install然后ng serve就可以跑起来了

**Comment by wanghaolu** [comment]
我用alain源码测试了一下，this.curUrl的值一直都不正确。
如下图显示，页面已经跳转到/dashboard/v1，但ReuseTabService中的curUrl任然是/dashboard/analysis


![tim 20180122171701](https://user-images.githubusercontent.com/9586655/35213229-da731b84-ff97-11e7-8831-6a7fccd5aaf7.png)

**Comment by wanghaolu** [comment]
@cipchk 你的0.6.4终于解决了那个active报错的问题了，可以在stackblitz上重现这个问题了
两个链接来回点，你看title变化
https://stackblitz.com/edit/ng-alain-setup-xucgum

**Comment by cipchk** [comment]
可以试着修改 `abc\reuse-tab\reuse-tab.service.js` 中 415 行：

```js
this.curUrl = ret ? '' : (url || this.getUrl(curr));
```

应该可以临时解决当前的问题

**Comment by wanghaolu** [comment]
这个我试过，确实可以解决问题。也可以在set title()中直接从ActivatedRoute获取url，跳过this.curUrl
