### ISSUE TITLE
i18n 默认语言与title问题

### ISSUE THREAD

**Issue by ada-hou** [cipchk/delon#28]
1、在I18NService中定义了default语言为中文，应该页面显示都是中文的，现在默认显示英文，在startup.service中加入this.settings.setLayout('lang', his.i18n.defaultLang);也不行
2、点击切换语言后，title标题没有切换成对应的语言，需要刷新后才可以显示正确的语言

**Comment by cipchk** [comment]
1、`setLayout` 只是布局信息的变更，变不会对语言进行切换，可以调用 [I18NService](https://github.com/cipchk/ng-alain/blob/master/src/app/layout/default/header/components/i18n.component.ts#L35) 相应方法。
2、的确存在这种情况。

**Comment by cipchk** [comment]
fixed `0.6.5`
