### ISSUE TITLE
angular-cli最新版本安装delon/cli的问题

### ISSUE THREAD

**Issue by limingyao-xx** [cipchk/delon#29]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>
![image](https://user-images.githubusercontent.com/2350389/35320194-ebf02aa0-011d-11e8-8a57-38d197d24669.png)

**Comment by cipchk** [comment]
麻烦进一步描述原因。

**Comment by limingyao-xx** [comment]
1、最新的angular-cli 1.6.5用了angular-devkit/core 0.0.28,angular-devkit/schematics 0.0.51
2、delon/cli 0.6.4要求angular-devkit/core 0.0.22,angular-devkit/schematics 0.0.42
3、安装了delon/cli 0.6.4要求的版本后创建新项目报错。

![image](https://user-images.githubusercontent.com/2350389/35321044-e3eab11a-0120-11e8-81fa-4790889d139f.png)

**Comment by cipchk** [comment]
尝试安装一下全局 typescript：

```bash
npm i -g typescript
```

**Comment by limingyao-xx** [comment]
![image](https://user-images.githubusercontent.com/2350389/35321213-8b548b88-0121-11e8-9e6b-4e114ad28557.png)

**Comment by cipchk** [comment]
我不确定你的目录结构是怎么样，建议在一个干净的目录下创建项目。

**Comment by limingyao-xx** [comment]
![image](https://user-images.githubusercontent.com/2350389/35321470-f9f757e6-0121-11e8-8464-b220852138e1.png)

我在一个空目录下创建项目也不可以。

**Comment by cipchk** [comment]
能否列印一下 `C:\Users\asdf\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@delon` 的目录结构？

我可以确信当前版本可用，或许可以考虑重装安装一个所有相关模块以及 `@delon/cli`

**Comment by limingyao-xx** [comment]
![image](https://user-images.githubusercontent.com/2350389/35322110-05798574-0124-11e8-815f-b3e1c0cffb73.png)
我目前的路径是这样的。

**Comment by cipchk** [comment]
我看你的 Npm 全局包路径，是你自定义过，我不确定会不会是因为这个原因可能引起的。暂时我没办法告诉你更多信息了，抱歉。

**Comment by limingyao-xx** [comment]
我刚才清空了所有的重新更新了，但是得到同样的结果。过程中唯一出现的问题就是npm提示的版本依赖问题了。。。

**Comment by cipchk** [comment]
尝试根据 http://ng-alain.com/docs/cli 再做一次。

**Comment by grubed** [comment]
我也遇到同样的问题

**Comment by grubed** [comment]
![image](https://user-images.githubusercontent.com/21269645/35372262-e32388de-01d3-11e8-9894-805e65c26d17.png)
![image](https://user-images.githubusercontent.com/21269645/35372281-f98f626e-01d3-11e8-9fdd-a9b3d4d5c4b5.png)
![image](https://user-images.githubusercontent.com/21269645/35372304-23ce60f2-01d4-11e8-9542-c0b4e72aaed1.png)

**Comment by grubed** [comment]
用上诉方法是可以成功的

**Comment by limingyao-xx** [comment]
# window(tips: replace your name)
cd C:\Users\asdf\AppData\Roaming\npm\node_modules
xcopy "@delon" "@angular\cli\node_modules\@delon" /s /e /y

找到原因了：因为这个路径复制错了。。。

**Comment by LambertW** [comment]
我是通过
C:\Program Files\nodejs\node_modules\npm\node_modules
里面复制 @delon -> @angular\cli 下面解决问题的

windows 10环境 + npm + cnpm

**Comment by cipchk** [comment]
0.6.6: 已更新相应文档
