### ISSUE TITLE
登录后menu数据未加载，导航菜单为空

### ISSUE THREAD

**Issue by apphost** [cipchk/delon#31]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[x] Bug report -> please search issues before submitting
[] Feature request
[ ] Documentation issue or request
</code></pre>

## Steps to reproduce
1、启用身份验证后，访问会被重定向到/passport/login，在login.component.ts中打印`this.menuService.menus`显示为空数组。

2、登录完成后，this.router.navigate(['/'])到首页，左侧导航菜单不显示。

## What is expected?

login后可以直接显示菜单

## What is actually happening?

login后需要再额外添加代码来加载menu数据，然后再转向首页

## Environment

<pre><code>
ng-alain version: 0.6.5
Angular version: 5.0.0
Browser:
- [x] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
`startup.service` 只会在 Angular 启动时执行一次，因此建议在 login 授权成功后再一次获取菜单数据。
