### ISSUE TITLE
simple-table [data] source produce duplicate request.

### ISSUE THREAD

**Issue by LambertW** [cipchk/delon#32]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Steps to reproduce

```html
<nz-card nzTitle="Demo">

  <simple-table #st [data]="products" [total]="total" [columns]="columns" [ps]="10" [reqReName]="{ ps: 'results', pi: 'page'}"
    (change)="change($event)" [isPageIndexReset]="true"></simple-table>
</nz-card>
````
```ts
import { Component, OnInit } from '@angular/core';
import { NzMessageService } from 'ng-zorro-antd'
import { SimpleTableColumn } from '@delon/abc';
import { ProductsService } from 'app/routes/products/services/products.service';

@Component({
  selector: 'app-simple-list',
  templateUrl: './simple-list.component.html',
  styles: []
})
export class SimpleListComponent implements OnInit {
  total: number;
  products: any[] = [];
  params = {};
  columns: SimpleTableColumn[] = [
    { title: '产品名称', index: 'name' },
    { title: '价格', index: 'price' }
  ];
  query = {
    name: ''
  }

  constructor(private msg: NzMessageService, private productsService: ProductsService) { }

  ngOnInit() {
    this.productsService.getProducts(1, 10, '', '', this.query)
      .subscribe((res: any) => {
        console.log(res);
        this.products = res.results;
        this.total = res.info.total;
      });
  }

  change(ret: any) {
    this.productsService.getProducts(ret.pi, ret.ps, '', '', this.query)
      .subscribe((res: any) => {
        this.products = res.results;
        this.total = res.info.total;
      });
  }
}
````
## What is expected?

Request url for only once.

## What is actually happening?

Requset url twice, and redirect to first page.
![image](https://user-images.githubusercontent.com/12291760/35520991-8e5fbd30-0553-11e8-9db0-b251394d817f.png)
![image](https://user-images.githubusercontent.com/12291760/35521035-acb63eee-0553-11e8-8a2d-e169ec116436.png)

## Environment

<pre><code>
ng-alain version: 0.6.0
Angular version: 5.0.0
Browser:
- [x] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by LambertW** [comment]
By the way, the document said that `url` is not suggest to use in future. But the demo website still use the `url` property to request. Please update the simple-table demo with `data` property, thx.

**Comment by cipchk** [comment]
i think trigger `change` is right when data from `[]` to `[10]` count.

BTW, i will remove `url` property in next minor version.

**Comment by LambertW** [comment]
If this is right logic, then what did I do to achieve the page index chang?
I
It always redirect to first page when I click page 2.

**Comment by cipchk** [comment]
or

```html
<simple-table #st></simple-table>
<button (click)="st.load()"></button>
<button (click)="st.reset()">重置</button>
```

**Comment by LambertW** [comment]
I change the `data` type from `[]` to `string`, and now it works well.
It's better to supply some description about how to use the different `data` type. Just like `[]` with none pagination.
![image](https://user-images.githubusercontent.com/12291760/35629475-b076d386-06d9-11e8-806b-fe5592534c05.png)

**Comment by cipchk** [comment]
Pls refer to the specific case examples
