### ISSUE TITLE
abc独立安装问题

### ISSUE THREAD

**Issue by ah-kevin** [cipchk/delon#34]
只要随便引入abc随便哪个module,
就会报错
![image](https://user-images.githubusercontent.com/10068519/35721097-78669eec-082b-11e8-8e29-9850325acea4.png)
是依赖了什么么..我基本上都装了啊

**Comment by ah-kevin** [comment]
![image](https://user-images.githubusercontent.com/10068519/35722310-bfec7818-0830-11e8-997c-1c00d6529430.png)

**Comment by ah-kevin** [comment]
ok了

**Comment by liyunfei0302** [comment]
我也遇到了，怎么回事？？
