### ISSUE TITLE
ACL 模块 权限点与角色的类型

### ISSUE THREAD

**Issue by CK110** [cipchk/delon#35]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link

```
export interface ACLType {
    /**
     * 角色
     *
     * @type {string[]}
     */
    role?: string[];
    /**
     * 权限点
     *
     * @type {(number[] | string[])}
     */
    ability?: number[] | string[];

    [key: string]: any;
}

export type ACLCanType = number | number[] | string | string[] | ACLType;
```

`role`与`ability` 都可以是string[] 类型，但是有些地方，认为string就是role，number就是ability，这里面是否有问题？导致我每次只能用ACLType，指定ability。

```
        {
            "text": "日常办公",
            "translate": "OA",
            "group": true,
            "children": [
                {
                    "text": "出勤休假",
                    "acl": {"ability":["oa_leave_list","oa_errand_list","oa_atmerrand_list"]},
                    "children": [
                        {
                            "text": "休假流程",
                            "link": "/oa/attend/leave",
                            "acl": {"ability":["oa_leave_list"]}
                        }
                    ]
                }
]
}
```

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
我们没有办法在一个属性上区分到底是 `role` or `ability`，因此在 `can()` 调用上默认是以 `string` 和 `number` 自动区分，若你们后端角色&权限点是用这两种类型区分则使用起来会很漂亮；但我们也只能这样子做，我们没办法在两个都是 string 的情况下在执行 `can()` 时到底是哪一个。

同时，`MenuService` 内部即是调用 `can()` 来处理 acl 部分。

当然在 `simple-table` 也是如此。
