### ISSUE TITLE
ACLService 按照官方设计当前用户权限应该何时获取？

### ISSUE THREAD

**Issue by CK110** [cipchk/delon#36]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[x] Feature request
[] Documentation issue or request
</code></pre>

## Reproduction link

在`StartService`中
```
       // ACL：设置权限为全量
       this.aclService.setFull(true);
```
在layout页面初始化的时候，获取用户权限，并且设置到内存中`aclService`
```
                this.aclService.setFull(false);
                this.aclService.set(acls);
```

这种方式，在刷新的时候，`ACLDirective`没有效果，原因是路由已经跳转了，但是`layout`的`ngOnInit`还没请求到用户权限(异步)，也就是说`ACLDirective`中的`ACLService`还没初始化数据。

目前我的处理方式，是在路由守卫上去获取用户权限，并设置到缓存中。

有没有什么方式`ACLService` 中`can()`方法执行之前，确保已经初始化用户权限到`ACLService`中了？

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
建议在 `StartService` 获取 用户权限。

**Comment by CK110** [comment]
StartService，是在应用初始化的时候调用，这里分2中情况:
1. 直接登录
2. 已经登录，执行刷新操作，对于这种情况，是可以在StartService中判断用户登录后存储的token信息获取用户权限

但是对于还没有执行登录操作的用户，如果在 StartService中 获取 用户权限，根本就不知道是去获取哪个用户的权限啊

**Comment by cipchk** [comment]
可以在授权成功后再一次获取一次用户权限，我想这些都只是业务逻辑处理问题吧。

**Comment by ada-hou** [comment]
设计到用户登录操作的系统，肯定需要两个地方获取用户权限
1、startservice 用于已登录情况和刷新
2、login的时候获取权限
其实还有菜单也是同样的问题

**Comment by cipchk** [comment]
说真的，我还是没明白你希望我能帮你什么？或者应该怎么做？

**Comment by CK110** [comment]
@cipchk 我这边的意思是，目前来说，alian的权限是在内存中的(aclService)，不能保证需要用到ACLDirective的时候，权限已经获取到了，alian 只是在start.service.ts 里面设置了全部权限。

但是这种问题并不是一个不能解决的问题，就是想知道alian会怎么处理而已！

**Comment by cipchk** [comment]
目前从逻辑的角度来说，分为两种情况：

- **已认证**：使用 `startup.service.ts`
- **未认证**：会直接跳转至登录页，可以在登录成功后重新调用一次 `startup.service.ts`，并成功后再跳转。
