### ISSUE TITLE
Menu如何支持 /info/:id 地址

### ISSUE THREAD

**Issue by apphost** [cipchk/delon#37]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[x] Documentation issue or request
</code></pre>

Menu设置中，如何支持`/info/:id`地址？如何使这样的页面自动展开导航菜单及正确显示面包屑导航？

**Comment by cipchk** [comment]
不支持这种写法。
