### ISSUE TITLE
MenuService 关于国际化、ACL、badge的一些问题

### ISSUE THREAD

**Issue by yixiangling** [cipchk/delon#42]
[delon/src/core/theme/services/menu/menu.service.ts](delon/src/core/theme/services/menu/menu.service.ts)

看了MenuService的设计，有些不同的看法

在MenuService中有包含国际化、ACL、badge等内容的处理，但我觉得MenuService还是保持对menu数据维护的纯粹性比较好，尽量不处理与界面表现相关的内容。

# 关于国际化
在MenuService中不处理国际化，而交由呈现菜单的组件来进行处理，组件模板中使用如translate pipe来处理国际化问题。

# 关于ACL
在MenuService中不处理acl信息，在组件呈现菜单时通过在模板中调用组件提供的方法，使用ACLService检查权限后来判断是否显示菜单。
其他导航性表现组件上也可以针对组件的特性来处理导航需求

## 需求示例
比如pro-header组件在生成breadcrumb的时候就可以有如 `首页>XX列表(无权限)>文档01` 的呈现方式，这些呈现与组件和acl有关，MenuService只提供导航结构完整数据和获取路径结构数据。
可以说这个需求自己去实现一个生成breadcrumb的组件，但实际在做的时候也只是用到了MenuService的菜单数据，说明MenuService处理acl是处理不干净的，既然这样索性不要处理acl相关的东西。

# 关于badge等
在MenuService中不处理badge等信息，菜单数据中也不记录badge相关的内容。将此需求的处理交给sidebar-nav等组件来处理，组件只需监听相关事件即可。
_Menu对象中可以提供一个类似name的属性，便于处理事件的组件找到该menu来处理_

# 变化
通过以上改动后，MenuService将不再需要resume方法来重置菜单。这样可以保持MenuService只对menu数据维护的纯粹性。

**Comment by cipchk** [comment]
`MenuService` 到底应该是贫血还是充血，我个人认为要看其目的是什么？Menu 包括一些东西，其目的不是单纯用来存储远程数据，她应该有更大的功能性。而这些功能性是为了简化开发工作，我们不希望开发者从 `MenuService` 获得的数据还需要进一步加工，因为AC好、国际化、徽标等这些参数会在各个地方被使用，例如：面包屑、主菜单等，保持系统的统一性更重要。

**Comment by yixiangling** [comment]
我觉得这不是贫血还是充血的问题，我只是谈职责划分或者说需求实现点归属的问题。`MenuService`维护菜单数据是理所当然，包括进行一些菜单逻辑的计算处理等等。但国际化、ACL、badge不是菜单业务逻辑，而是菜单呈现逻辑，最好还是归属到呈现部分去处理。

我觉得还是不要讨论贫血还是充血的问题，我做后端的真的很不喜欢这个讨论，代码具体如何组织是一个符合设计模式非常自然的结果，包括领域驱动设计的权威著作（主要指Eric Evans的经典著作）从来没有提到所谓贫血或充血的模型选择。因此只谈`MenuService`的职责划分问题比较好。

**Comment by cipchk** [comment]
你可以自行覆盖 `MenuService`，ng-alain 目前不会做任何改变，感谢关注。
