### ISSUE TITLE
SimpleTable的buttons希望能添加根据不同条件决定button是否显示的功能

### ISSUE THREAD

**Issue by fengweilin** [cipchk/delon#43]
我希望根据表格内订单的状态来显示不同的操作按钮，例如在订单状态为已关闭的情况下，不显示「添加面试时间」「面试通过」等按钮，目前的api无法实现。
![image](https://user-images.githubusercontent.com/2265045/37239212-67495196-2472-11e8-9173-95a66770965b.png)

**Comment by cipchk** [comment]
目前只能使用自定义列的方式解决；

已经在考虑这方面。

**Comment by fengweilin** [comment]
好的，谢谢

**Comment by cipchk** [comment]
fixed 1.0.0-beta
