### ISSUE TITLE
ReuseTab of the same type

### ISSUE THREAD

**Issue by pucheoswaldo** [cipchk/delon#45]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ x ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

How to add several ReuseTab of the same type? Example I have a client list and I would like to create several Tab for each client that I am touching.
![image](https://user-images.githubusercontent.com/8845581/37406384-6ab9018e-276d-11e8-8fa5-697043442f69.png)

## What is actually happening?

Currently update ReuseTab (Customer 'X')
![image](https://user-images.githubusercontent.com/8845581/37406482-a0a2ddc4-276d-11e8-85e5-eca5313ebf82.png)
![image](https://user-images.githubusercontent.com/8845581/37406647-0297d372-276e-11e8-88e3-4930b43b26c1.png)
![image](https://user-images.githubusercontent.com/8845581/37406678-1c0e8e68-276e-11e8-991c-3c5ff9deb634.png)

## Environment

<pre><code>
ng-alain version: 0.6.7
Angular version: 5.0.0
Browser:
- [ X ] Chrome (desktop)
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
pls upgrade @delon/* libs to laster version.

**Comment by pucheoswaldo** [comment]
Thank you! I'm ready 0.8.0, but I still can not create multiple tabs (customer/: id), customer/1, customer/2, customer/3 ... 
![](https://user-images.githubusercontent.com/8845581/37406384-6ab9018e-276d-11e8-8fa5-697043442f69.png)

**Comment by cipchk** [comment]
you can add `reuse` property in router config, abort more information go to [ng-alain.com](http://ng-alain.com/components/reuse-tab#%E5%8C%B9%E9%85%8D%E6%A8%A1%E5%BC%8F)

**Comment by pucheoswaldo** [comment]
Wow so cool, u r amazing 👍 🙂
