### ISSUE TITLE
AdNumberToChineseModule不存在

### ISSUE THREAD

**Issue by wenzhijie** [cipchk/delon#46]
ng new -c=@delon/cli my-app 指令，生成项目中，delon.module.ts报AdNumberToChineseModule不存在，发现node_modules，@delon/abc不存在number-to-chinese目录，
![1](https://user-images.githubusercontent.com/11324524/37633890-214290da-2c2f-11e8-8338-c9ed96e04515.png)
![2](https://user-images.githubusercontent.com/11324524/37633891-2188b4b6-2c2f-11e8-8695-6832b7c8015c.png)

**Comment by cipchk** [comment]
可能 是 `@delon` 版本太低
