### ISSUE TITLE
jwt拦截器的问题

### ISSUE THREAD

**Issue by ziben** [cipchk/delon#5]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

jwt拦截器从tokenservice中取出来的model只是一个纯粹的对象。

## Expected behavior

取出来的应该是一个JWTTokenModel

## Environment

<pre><code>
Angular version: 5.1.0

delon version: 0.3.0

Browser:
- [ x ] Chrome (desktop) version 63
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Windows 

Others:

</code></pre>

**Comment by cipchk** [comment]
`TokenService` 得到的是一个 `ITokenModel` 接口，而 `JWTTokenModel` 继承于它，因此当你明确知道自己是JWT，则可以这样：

```ts
const jwtModel = tokenService.get() as JWTTokenModel;
```

**Comment by ziben** [comment]
嗯，我看src里有这个，但是安装后的那个js里面没有了后面那个as，不知道是不是编译成js的时候去掉了。

**Comment by cipchk** [comment]
npm 上是 es5 代码，`as` 这是 typescript 语句，二者不一样。

**Comment by ziben** [comment]
我知道这两个是不一样的。

所以，你这个编译到es5后，代码中引用包里的拦截器，是不好用的，得到的只是一个存粹的object，没有静态方法。

我把你的拦截器代码整个拷贝到我的代码目录中，里面是用的as转换，但是也不好用，难道是我的ts版本不对么？

我用的ts是2.5.3版本的。

**Comment by ziben** [comment]
`        const model = new JWTTokenModel();
        const data = this.injector.get(DA_SERVICE_TOKEN).get() as JWTTokenModel;
        console.log(data);
        Object.assign(model, data);`

**Comment by cipchk** [comment]
现在反而我完全无法理解你需要我帮你什么？

**Comment by ziben** [comment]
我觉得这是一个bug。

我引入了JWTInterceptor到我的项目，但是运行时，发现有问题，控制台打印出：model.isExpired这个方法不存在。

我跟踪了一下，发现this.injector.get(DA_SERVICE_TOKEN).get()，这个取出来后不是JWTTokenModel，所以没有那个方法。

我改造了一下，代码就是我上面贴出来的，这样就好用了。

**Comment by ziben** [comment]
我根据你说的，觉得可能是编译成es5后丢失了类型信息，所以就单独把jwt.interceptor.ts文件复制到项目目录下，发现即使用了`as JWTTokenModel`，还是不行。

代码里那个console.log(data)是我为了调式打出来的，可以无视。

**Comment by cipchk** [comment]
```ts
this.injector.get(DA_SERVICE_TOKEN).get() as JWTTokenModel
```

应该这样子写，另外 console，应该是无法打印，原因是 `isExpired` 是一个方法，而不是一个具体的属性。

**Comment by ziben** [comment]
![image](https://user-images.githubusercontent.com/614036/34034722-97367ab4-e1ba-11e7-8486-b58488dd5690.png)

console可以打印出类型信息的。

**Comment by cipchk** [comment]
我再一次被你弄晕了。

若有实际 BUG，是否能给我一明确的信息，以及一个在线 Plunk，这样方便我定位问题的根源。谢谢。

**Comment by ziben** [comment]
这样说吧， JWTInterceptor在取出保存在storage中的token信息的时候，得到的并不是一个JWTTokenModel的实例，没有isExpired这个方法。

**Comment by cipchk** [comment]
我可以明确一点 [jwt.interceptor.ts](https://github.com/cipchk/delon/blob/master/src/core/auth/token/jwt/jwt.interceptor.ts#L33) 可以正确获取所需要的信息，这一点在[测试用例](https://github.com/cipchk/delon/blob/master/src/core/auth/token/jwt/jwt.interceptor.ts#L30)当中也能正确获取，因此我认为应该这方面没有问题。

**Comment by ziben** [comment]
我是在实际使用中发现的这个问题，难道是我的用法有问题？
1、AppModule中引入拦截器
```typescript
{ provide: HTTP_INTERCEPTORS, useClass: JWTInterceptor, multi: true },
```
2、 登录成功后，把token放入tokenservice中
```typescript
const tokenModel = new JWTTokenModel();
tokenModel.token = token;
this.tokenService.set(tokenModel);
```
3、在后续访问其他api的时候，拦截器就会在控制台报错，经过单步跟踪和调试，确认是这个问题。

------
你那个测试用例我看了，用的MockTokenService，直接作为属性来存取TokenModel，当然不会有问题。实际中用的是LocalStorage，取出来是没有我所需要的信息的。

**Comment by ziben** [comment]
我还不知道plunker怎么引入你这个库

**Comment by cipchk** [comment]
https://cipchk.github.io/ng-alain/pro/user/login 这是一个完整的 DEMO，也是没有问题的。

**Comment by ziben** [comment]
这个DEMO用的是SimpleInterceptor吧，没有用JwtInterceptor啊

**Comment by cipchk** [comment]
我晚点再核实一下这个问题。

**Comment by ziben** [comment]
TokenService没问题了，但是jwt.interceptor.ts这个文件里面还没有修正。

需要修改成
```typescript
const model = this.injector.get(DA_SERVICE_TOKEN).get(JWTTokenModel);
```
