### ISSUE TITLE
请教一下，下载源码后无法打包，报版本不对，打包是否有相关的版本要求吗？

### ISSUE THREAD

**Issue by 200688523** [cipchk/delon#6]
> delon@0.4.1 site:cname E:\002_jsproject\three_open_project\delon
> cname site/dist

'cname' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "site:cname"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! delon@0.4.1 site:cname: `cname site/dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the delon@0.4.1 site:cname script 'cname site/dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the delon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cname site/dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs delon
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls delon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\002_jsproject\three_open_project\delon\npm-debug.log
ERROR: "site:cname" exited with 1.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "site:build"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! delon@0.4.1 site:build: `npm-run-all -s site:clean site:gen site:ts site:cname`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the delon@0.4.1 site:build script 'npm-run-all -s site:clean site:gen site:ts site:cname'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the delon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all -s site:clean site:gen site:ts site:cname
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs delon
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls delon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\002_jsproject\three_open_project\delon\npm-debug.log
ERROR: "site:build" exited with 1.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "site:release"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! delon@0.4.1 site:release: `npm-run-all -s site:build site:404 site:deploy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the delon@0.4.1 site:release script 'npm-run-all -s site:build site:404 site:deploy'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the delon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all -s site:build site:404 site:deploy
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs delon
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls delon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\002_jsproject\three_open_project\delon\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "release"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! delon@0.4.1 release: `npm run version:bump && npm run release:prepare && npm publish --access=public .lib/theme && npm publish --access=public .lib/abc && npm publish --access=public .lib/acl && npm publish --access=public .lib/auth && npm run site:release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the delon@0.4.1 release script 'npm run version:bump && npm run release:prepare && npm publish --access=public .lib/theme && npm publish --access=public .lib/abc && npm publish --access=public .lib/acl && npm publish --access=public .lib/auth && npm run site:release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the delon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run version:bump && npm run release:prepare && npm publish --access=public .lib/theme && npm publish --access=public .lib/abc && npm publish --access=public .lib/acl && npm publish --access=public .lib/auth && npm run site:release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs delon
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls delon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\002_jsproject\three_open_project\delon\npm-debug.log

**Comment by cipchk** [comment]
`site:cname` 是为了 gh-pages 所需要，依赖 `cname` 类库，你可以全局安装一下它。
