### ISSUE TITLE
simple-table使用st.load(1)搜索刷新页面，页码不会变化！

### ISSUE THREAD

**Issue by s-panjy** [cipchk/delon#63]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Steps to reproduce

 <simple-table #st [columns]="columns" [data]="data" [loading]="loading"
        (checkboxChange)="checkboxChange($event)"
        (filterChange)="getData()"
        pagePlacement="center" toTopInChange
        showSizeChanger showQuickJumper showTotal isPageIndexReset
        >
        <ng-template st-row="status" let-i>
            <nz-badge [nzStatus]="i.statusType" [nzText]="i.statusText"></nz-badge>
        </ng-template>
    </simple-table>

<button nz-button (click)="st.load(1)" [nzType]="'primary'" [nzLoading]="http.loading">搜索</button>
                
首先加载全部数据到表格中，比如有300条数据，每页10条，页码为30，然后使用条件搜索，数据刷新后，页码依然为30页，不会刷新，但是选中30页会显示为空

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
b. 若是bug，请填写复现步骤、在线演示（模板：https://stackblitz.com/edit/ng-alain-setup?file=app%2Fapp.component.ts）

**Comment by s-panjy** [comment]
https://cipchk.github.io/ng-alain/#/pro/list/table-list
规则编号:TradeCode 0 点击搜索 页码依然为5页
