### ISSUE TITLE
request url contains 'login',token will be ignored

### ISSUE THREAD

**Issue by renmengting** [cipchk/delon#70]
比如我向后台发送请求的网址是'/management/login-logs'，请求就不带token了，查了下是正则匹配的问题，不知道算不算个bug
https://github.com/cipchk/delon/blob/779e91a706ae491e0f27c656c0fefd1219d9fa5b/packages/auth/auth.config.ts#L40

**Comment by cipchk** [comment]
非也，你可以直接覆盖这些默认值。
