### ISSUE TITLE
page-header 是否可以设置成固定,不随页面滚动而滚动

### ISSUE THREAD

**Issue by Ants24** [cipchk/delon#71]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

page-header 可以设置成固定,不随页面滚动而滚动

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
统一关注另一个issues：https://github.com/cipchk/ng-alain/issues/609

暂时关闭。
