### ISSUE TITLE
SimpleTable Buttons 有下拉按钮时,不能使用图标

### ISSUE THREAD

**Issue by hemiaoio** [cipchk/delon#78]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
已经修复
