### ISSUE TITLE
menu.service 的getPathByUrl方法无法对lazyload的url进行匹配

### ISSUE THREAD

**Issue by wanghaolu** [cipchk/delon#9]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

通过lazyload加载的模块无法用getPathByUrl获取

![1](https://user-images.githubusercontent.com/9586655/34367576-4f4b8556-eae7-11e7-9e98-01b6f9b2c5ca.png)

我这里的AdminModule和OtherModule是分为不同用户使用的，他们权限各不相同，在进入不同模块后再初始化menu，这样就导致了获得的url地址包含了上级模块的路由地址，但在menu中配置的并没有上级路由地址，就导致了匹配失败。
针对这种需求有没有什么好的解决方案

**Comment by cipchk** [comment]
`0.4.2` 新增了一个 `MenuService.change` 可用于监听菜单变化，你可以在根组件里进行监听，当菜单数据发生变化时重新获取一次，我想应该可以解决这一问题。

**Comment by wanghaolu** [comment]
这个问题主要是导致了reuse-tab没法找到正确的menu

![tim 20171228172752](https://user-images.githubusercontent.com/9586655/34406538-9b9a422c-ebf4-11e7-89a3-828363449d04.png)

**Comment by cipchk** [comment]
可以在监听时重置当前标签文本。

```ts
export class DemoReuseTabEditComponent implements OnInit {
    id: any;

    constructor(private route: ActivatedRoute, private reuseTabService: ReuseTabService) {}

    ngOnInit(): void {
        this.route.params.subscribe(params => {
            this.id = params.id;
            this.reuseTabService.title = `编辑 ${this.id}`;
        });
    }
}
```

**Comment by cipchk** [comment]
长时间未处理；有任何问题重新提交issues。
