### ISSUE TITLE
desc-list does not support ngFor

### ISSUE THREAD

**Issue by gsbybb** [cipchk/delon#93]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link
https://stackblitz.com/edit/ng-alain-setup-fh3s3m

## What is expected?

可以通过ngFor挂载desc-list-item

## What is actually happening?

会报错

![image](https://user-images.githubusercontent.com/13886444/41023610-76062502-699f-11e8-855d-8397ca410bd5.png)

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
已知BUG，已经修复，下一版本会修复。
